# ======================================
# Configuración de Render para Deploy Automático
# ======================================
# Documentación: https://docs.render.com/blueprint-spec

services:
  # Servicio Web (API Spring Boot)
  - type: web
    name: usuarios-api
    runtime: docker
    plan: free  # Opciones: free, starter, standard, pro

    # Región del servidor (elige la más cercana a tus usuarios)
    region: oregon  # Opciones: oregon, frankfurt, singapore, ohio

    # Branch de GitHub/GitLab a desplegar
    branch: main

    # Archivo Dockerfile a usar
    dockerfilePath: ./Dockerfile

    # Comando de healthcheck (opcional, Docker ya tiene HEALTHCHECK)
    healthCheckPath: /api/usuarios

    # Variables de entorno
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: prod  # Cambia a 'dev' si necesitas logs SQL y consola H2

      - key: JPA_SHOW_SQL
        value: false  # Cambia a 'true' para ver queries SQL en logs

      - key: H2_CONSOLE_ENABLED
        value: false  # NO HABILITAR EN PRODUCCIÓN (riesgo de seguridad)

      # Optimización JVM para contenedores con recursos limitados
      - key: JAVA_OPTS
        value: -XX:+UseContainerSupport -XX:MaxRAMPercentage=75.0 -Xms256m -Xmx512m

    # Auto-deploy cuando se hace push al branch
    autoDeploy: true

    # Configuración de escalado (solo planes de pago)
    # scaling:
    #   minInstances: 1
    #   maxInstances: 3

    # Recursos (solo planes de pago, free tiene recursos fijos)
    # disk:
    #   name: data
    #   mountPath: /data
    #   sizeGB: 1